sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
# this is my openssl for my encrypted google secret key from json file.
  - openssl aes-256-cbc -K $encrypted_5ec6ae011e27_key -iv $encrypted_5ec6ae011e27_iv -in service.account.json.enc -out service.account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # my file is service.account.json.enc and so use service.account.json as output. see above.
  - gcloud auth activate-service-account --key-file service.account.json
  # my project is multi-k8s-383721
  - gcloud config set project multi-k8s-383721
  # my compute zone is us-west2-a
  - gcloud config set compute/zone us-west2-a
  # cluster is needed for kubectl commands. My cluster is multi-cluster
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stephengrider/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master