name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t dave123456789/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true dave123456789/react-test npm test
 
      - run: docker build -t dave123456789/multi-client-10-14 ./client
      - run: docker build -t dave123456789/multi-nginx-10-14 ./nginx
      - run: docker build -t dave123456789/multi-server-10-14 ./server
      - run: docker build -t dave123456789/multi-worker-10-14 ./worker
 
      - run: docker push dave123456789/multi-client-10-14
      - run: docker push dave123456789/multi-nginx-10-14
      - run: docker push dave123456789/multi-server-10-14
      - run: docker push dave123456789/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multigh-env
          existing_bucket_name: elasticbeanstalk-us-west-1-725291656587
          region: us-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip