name: Deploy MultiK8s
on:
  workflow_run:
    workflows: Frontend unit tests
    branches: [master]
    types: completed
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    permissions:
      contents: 'read'
      id-token: 'write'
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t dave123456789/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true dave123456789/react-test npm test
 
      - name: Set Identity Provider
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/938212450194/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-deployer-wif@multi-k8s-wif-384321.iam.gserviceaccount.com'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-wif-384321
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster-wif
          location: us-west2-a 
 
      - name: Build
        run: |-
          docker build -t dave123456789/multi-client-k8s-gh-wif:latest -t dave123456789/multi-client-k8s-gh-wif:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t dave123456789/multi-server-k8s-pgfix-gh-wif:latest -t dave123456789/multi-server-k8s-pgfix-gh-wif:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t dave123456789/multi-worker-k8s-gh-wif:latest -t dave123456789/multi-worker-k8s-gh-wif:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push dave123456789/multi-client-k8s-gh-wif:latest
          docker push dave123456789/multi-server-k8s-pgfix-gh-wif:latest
          docker push dave123456789/multi-worker-k8s-gh-wif:latest
 
          docker push dave123456789/multi-client-k8s-gh-wif:${{ env.SHA }}
          docker push dave123456789/multi-server-k8s-pgfix-gh-wif:${{ env.SHA }}
          docker push dave123456789/multi-worker-k8s-gh-wif:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=dave123456789/multi-server-k8s-pgfix-gh-wif:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=dave123456789/multi-client-k8s-gh-wif:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=dave123456789/multi-worker-k8s-gh-wif:${{ env.SHA }}